### ISSUE TITLE
Observações sobre o MER

### ISSUE THREAD

**Issue by ericknilsen** [pino/probex#12]
- Um usuário não deveria possuir pelo menos uma permissão?
- 1...n Posts recebe votos de 0..n usuários

**Comment by levi-rocha** [comment]
- A permissao padrao (default) nao possuira uma tupla na tabela, pois todos usuarios possuirao ela. Por isso, um usuario sem nenhuma permissao e automaticamente um usuario padrao. Portanto, o usuario pode sim nao ter permissao.
- Um usuario pode nao votar em nenhum post. Portanto, o relacionamento e 0...n, 0...n
